# 1
FROM node:18.9-alpine AS builder

WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
RUN npm run build && npm prune --production


# 2
FROM node:18.9-alpine

USER node:node
WORKDIR /app
COPY --from=builder --chown=node:node /app/build ./build
COPY --from=builder --chown=node:node /app/node_modules ./node_modules
COPY package.json .

EXPOSE 3000

CMD [ "node", "build" ]