FROM postgres:15rc1-alpine

COPY schema.sql /docker-entrypoint-initdb.d/

ENV POSTGRES_PASSWORD="docker_database"
ENV POSTGRES_DB="mytwitch"
ENV PGDATA=/var/lib/postgresql/data/pgdata
ENV TZ=Asia/Seoul

EXPOSE 5432

CMD ["postgres"]